pipeline {

    agent any

    environment {

        IMAGE_NAME = "flask-demo"
        IMAGE_TAG  = "1.0.0"

        NEXUS_URL  = "http://localhost:8081"

    }

    stages {

        stage('Checkout') {

            steps {
                checkout scm
            }

        }

        stage('Install Dependencies') {

            steps {
                sh 'python3 -m pip install -r app/requirements.txt'
            }

        }

        stage('Run Tests') {

            steps {
                sh 'pytest tests'
            }

        }

        stage('Build Docker Image') {

            steps {

                sh '''
                docker build \
                -t ${IMAGE_NAME}:${IMAGE_TAG} app
                '''

            }

        }

        stage('Docker Login (Nexus)') {

            steps {

                withCredentials([
                    usernamePassword(
                        credentialsId: 'nexus-creds',
                        usernameVariable: 'NEXUS_USER',
                        passwordVariable: 'NEXUS_PASS'
                    )
                ]) {

                    sh '''
                    echo "$NEXUS_PASS" | docker login \
                    localhost:8082 \
                    -u "$NEXUS_USER" \
                    --password-stdin
                    '''

                }

            }

        }

        stage('Push Image') {

            steps {

                sh '''
                docker tag \
                ${IMAGE_NAME}:${IMAGE_TAG} \
                localhost:8082/${IMAGE_NAME}:${IMAGE_TAG}

                docker push \
                localhost:8082/${IMAGE_NAME}:${IMAGE_TAG}
                '''

            }

        }

    }

    post {

        success {

            echo "Artifact Published Successfully"

        }

        failure {

            echo "Pipeline Failed"

        }

    }

}
