pipeline {

    agent any

    environment {
        IMAGE_NAME = "flask-demo"
        IMAGE_TAG  = "1.0.0"
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Install Dependencies') {
            steps {
                sh 'python3 -m pip install -r app/requirements.txt'
            }
        }

        stage('Run Tests') {
            steps {
                sh 'pytest tests'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t ${IMAGE_NAME}:${IMAGE_TAG} app'
            }
        }

        stage('Apply Constraint Templates') {
            steps {
                sh 'kubectl apply -f gatekeeper/'
            }
        }

        stage('Validate Gatekeeper Policies') {
            steps {
                sh '''
                mkdir -p reports

                kubectl get constrainttemplates \
                > reports/constrainttemplates.txt

                kubectl get constraints \
                > reports/constraints.txt
                '''
            }
        }

    }

    post {

        always {
            archiveArtifacts artifacts: 'reports/*'
        }

        success {
            echo "OPA Gatekeeper Validation Successful"
        }

        failure {
            echo "OPA Gatekeeper Validation Failed"
        }

    }

}
