pipeline {

    agent any

    environment {

        IMAGE_NAME = "flask-demo"
        IMAGE_TAG  = "1.0.0"

    }

    stages {

        stage('Checkout') {

            steps {

                checkout scm

            }

        }

        stage('Install Dependencies') {

            steps {

                sh 'python3 -m pip install -r app/requirements.txt'

            }

        }

        stage('Run Tests') {

            steps {

                sh 'pytest tests'

            }

        }

        stage('Build Docker Image') {

            steps {

                sh '''
                docker build \
                -t ${IMAGE_NAME}:${IMAGE_TAG} app
                '''

            }

        }

        stage('Generate SBOM') {

            steps {

                sh '''
                mkdir -p reports

                syft ${IMAGE_NAME}:${IMAGE_TAG} \
                -o spdx-json=reports/sbom-spdx.json

                syft ${IMAGE_NAME}:${IMAGE_TAG} \
                -o cyclonedx-json=reports/sbom-cyclonedx.json

                syft ${IMAGE_NAME}:${IMAGE_TAG} \
                -o table=reports/sbom.txt
                '''

            }

        }

    }

    post {

        always {

            archiveArtifacts artifacts: 'reports/*'

        }

        success {

            echo "SBOM Generated Successfully"

        }

        failure {

            echo "SBOM Generation Failed"

        }

    }

}
