pipeline {

    agent any

    environment {
        IMAGE_NAME = "flask-demo"
        IMAGE_TAG  = "1.0.0"
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t ${IMAGE_NAME}:${IMAGE_TAG} app'
            }
        }

        stage('Run Unit Tests') {
            steps {
                sh 'pytest tests'
            }
        }

        stage('Apply Kyverno Policies') {
            steps {
                sh '''
                kubectl apply -f kyverno/
                '''
            }
        }

        stage('Validate Policies') {
            steps {
                sh '''
                kubectl get clusterpolicy

                kubectl describe clusterpolicy \
                require-signed-images \
                > reports/policy-report.txt
                '''
            }
        }

    }

    post {

        always {

            archiveArtifacts artifacts: 'reports/*'

        }

        success {

            echo "Kyverno Policy Validation Successful"

        }

        failure {

            echo "Kyverno Policy Validation Failed"

        }

    }

}
