pipeline {

    agent any

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t devsecops-flask:v2 ./app'
            }
        }

        stage('Docker Images') {
            steps {
                sh 'docker images'
            }
        }

        stage('Verify Container') {
            steps {
                sh 'echo Docker image built successfully'
            }
        }

    }

}
