pipeline {

    agent any

    parameters {

        choice(
            name: 'ENVIRONMENT',
            choices: ['dev','qa','stage','prod'],
            description: 'Deployment Environment'
        )

        string(
            name: 'VERSION',
            defaultValue: 'v1.0.0',
            description: 'Application Version'
        )

        booleanParam(
            name: 'RUN_TESTS',
            defaultValue: true,
            description: 'Execute Unit Tests'
        )
    }

    environment {
        IMAGE_NAME = "multibranch-demo"
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Print Parameters') {
            steps {
                echo "Environment : ${params.ENVIRONMENT}"
                echo "Version     : ${params.VERSION}"
                echo "Branch      : ${env.BRANCH_NAME}"
            }
        }

        stage('Install Dependencies') {
            steps {
                sh 'python3 -m pip install -r app/requirements.txt'
            }
        }

        stage('Run Tests') {
            when {
                expression { params.RUN_TESTS }
            }
            steps {
                sh 'pytest tests'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t ${IMAGE_NAME}:${params.VERSION} app'
            }
        }

        stage('Docker Images') {
            steps {
                sh 'docker images'
            }
        }
    }

    post {
        success {
            echo 'Pipeline Executed Successfully'
        }
        failure {
            echo 'Pipeline Failed'
        }
    }
}
