pipeline {

    agent any

    environment {

        IMAGE_NAME="github-flask"
        IMAGE_TAG="v1"

    }

    stages {

        stage('Checkout') {

            steps {

                checkout scm

            }

        }

        stage('Install Dependencies') {

            steps {

                sh 'python3 -m pip install -r app/requirements.txt'

            }

        }

        stage('Run Tests') {

            steps {

                sh 'pytest tests'

            }

        }

        stage('Build Docker Image') {

            steps {

                sh 'docker build -t ${IMAGE_NAME}:${IMAGE_TAG} app'

            }

        }

        stage('Verify Image') {

            steps {

                sh 'docker images'

            }

        }

    }

    post {

        success {

            echo 'GitHub Pipeline Completed Successfully'

        }

        failure {

            echo 'Pipeline Failed'

        }

    }

}
