@Library('devsecops-shared-library') _

pipeline {

    agent any

    environment {
        IMAGE_NAME = "shared-library-demo"
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                buildApp()
            }
        }

        stage('Deploy') {
            steps {
                deployApp("development")
            }
        }

        stage('Notification') {
            steps {
                notifyPipeline("SUCCESS")
            }
        }

    }

    post {

        failure {

            script {
                notifyPipeline("FAILED")
            }

        }

    }

}
