apiVersion: apps/v1
kind: Deployment
metadata:
  name: version-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: version-demo
  template:
    metadata:
      labels:
        app: version-demo
    spec:
      containers:
      - name: version-demo
        image: localhost:5000/flask-demo:1.0.0
        ports:
        - containerPort: 5000
