apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-demo
  template:
    metadata:
      labels:
        app: jenkins-demo
    spec:
      containers:
      - name: flask
        image: jenkins-flask:v1
        ports:
        - containerPort: 5000
