apiVersion: apps/v1
kind: Deployment
metadata:
  name: trivy-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trivy-demo
  template:
    metadata:
      labels:
        app: trivy-demo
    spec:
      containers:
      - name: trivy-demo
        image: flask-demo:1.0.0
        ports:
        - containerPort: 5000
