apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-network
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-network
  template:
    metadata:
      labels:
        app: flask-network
    spec:
      containers:
      - name: flask-network
        image: devsecops-flask:v5
        ports:
        - containerPort: 5000
