apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexus-demo
  template:
    metadata:
      labels:
        app: nexus-demo
    spec:
      containers:
      - name: nexus-demo
        image: localhost:8082/flask-demo:1.0.0
        ports:
        - containerPort: 5000
