pipeline {

    agent any

    stages {

        stage('Install Dependencies') {

            steps {

                sh 'pip install -r app/requirements.txt'

            }

        }

        stage('Run Tests') {

            steps {

                sh 'pytest'

            }

        }

    }

}
