pipeline {

    agent any

    environment {

        IMAGE_NAME = "jenkins-flask:v1"

    }

    stages {

        stage('Checkout') {

            steps {

                checkout scm

            }

        }

        stage('Install Dependencies') {

            steps {

                sh 'python3 -m pip install -r app/requirements.txt'

            }

        }

        stage('Run Tests') {

            steps {

                sh 'pytest tests'

            }

        }

        stage('Build Docker Image') {

            steps {

                sh 'docker build -t ${IMAGE_NAME} app'

            }

        }

        stage('Verify Docker') {

            steps {

                sh 'docker images'

            }

        }

    }

    post {

        success {

            echo 'Pipeline Completed Successfully'

        }

        failure {

            echo 'Pipeline Failed'

        }

    }

}
